name: Send to WhatsApp

on:
  push:
    branches:
      - main  # or the branch you want to monitor

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get the latest file
      id: get_latest_file
      run: echo "::set-output name=file::$(git ls-files -o | tail -1)"

    - name: Send file to WhatsApp
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Run script
      env:
        FILE: ${{ steps.get_latest_file.outputs.file }}
        WHATSAPP_GROUP_NAME: 'YOUR_WHATSAPP_GROUP_NAME'
      run: python send_to_whatsapp.py
